--- 
apiVersion: v1
kind: Service
metadata: 
  name: mysql
  namespace: drupal
spec: 
  selector: 
    app: mysql
  ports: 
    - name: mysql
      port: 3306
      protocol: TCP
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: drupal
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers: 
      - name: mysql
        image: mysql:5.7
        env: 
          - name: MYSQL_ROOT_PASSWORD
            value: root_password
          - name: MYSQL_DATABASE
            value: drupal-database
        ports: 
          - name: mysql
            containerPort: 3306
            protocol: TCP
        volumeMounts: 
          - name: vol-drupal 
            mountPath: /var/lib/mysql
            subPath: dbdata
      volumes: 
      - name: vol-drupal
        persistentVolumeClaim: 
          claimName: drupal-pvc-mysql